services:
  - type: web
    name: mlb-win-probability-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py dashboard.wsgi:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

